### ISSUE TITLE
Config File not generating? [SOLVED PROBABLY]

### ISSUE THREAD

**Issue by Vivid141** [quat1024/apathy#14]
Ok, so I've loaded up the game and launched it to generate Apathy's config file in order to change things around, but when I check the Apathy folder in my config file directory, the folder's empty.
![image](https://user-images.githubusercontent.com/113260721/194709329-8ca023f6-b9b7-4001-990a-a9d9c10d25df.png)
![image](https://user-images.githubusercontent.com/113260721/194709339-2eb66a36-cf8d-45ad-932e-4d17330f97fd.png)

Any suggestions for how to fix this? Can I download the config file separately and insert it into the Apathy folder?

**Comment by quat1024** [comment]
Config stuff is generated a bit late; open a world at least once

**Comment by Vivid141** [comment]
Oh ok, thanks :)

**Comment by quat1024** [comment]
There used to be some bugs where apathy read its config file before other mods registered their stuff, which broke the config pretty badly (#9). It also reads the config file on every data load, which occurs when you do the `/reload` command but also when you start the server for the first time. That config load doesn't break in the way #9 does because the entity registry has long since been populated by the time datapack loading happens. ~~which will change by the time mojang adds datapack mobs.~~

There are cleaner ways to wait for after all other mods to load and register their entities *on Forge* but i dont think fabric has a good event for that. And i needed to make the change for six versions of minecraft without spending hours testing them all (srry). So i just removed the startup config load and let the datapack configload take care of it, which was a small enough change that i felt alright about it.

But yeah, since loading the config is what causes the file to appear if it doesnt exist, it does appear significantly later than most other mod config files. Hopefully that makes sense
