### ISSUE TITLE
[Request 1.19.2 Fabric] - Gui Option + turn based

### ISSUE THREAD

**Issue by DemonSlayer112** [quat1024/apathy#18]
I like the idea of this mod quite a lot!
But would be great if we could enable/disable in game via difficulty.
`/difficulty apathy` or maybe the name of the difficulty mode can be set in the config for more customization :D

Also, would it be possible to make mobs battle turn based?
If you hit zombie, zombie hits you, then you hit zombie back, making zombie invulerable after you hit once(or miss ;) )
I would assume moving via WASD would also count as a move, so if you run they will chase as normal.

**Comment by quat1024** [comment]
Adding a new difficulty requires an enum extension (a *ridiculously* brittle hack) and modifying the ~20-30 places the game checks the difficulty. It's not worth it, especially with the support workload this mod already requires.

I chose to commandeer the vanilla difficulty system because there's basically no difference between Easy and Normal in vanilla; you can use this mod to create more of a distinction. The "player sets" feature can also be used to create a parallel experience.

Turn based combat doesn't make much sense because you're almost always moving. That might be cool in a separate mod but i dont think it fits here
