### ISSUE TITLE
Question Re: Configuration

### ISSUE THREAD

**Issue by Full-Course-Identity** [quat1024/apathy#29]
Hi! I saw on your landing page that you don't mind questions being asked via Issues, so I hope you don't mind this!

Context -- I'm very, very new to... well, just about everything both Minecraft & its modding scene (only started playing the game this year). As a result, I have, like, -1 intellect re: tweaking config files. I managed to figure out just enough to turn on the nuclear option, but... I have pretty bad ADHD, & in conjunction w/ my sheer Unfamiliarity towards coding logic in general, my eyes just kinda glaze over every time I open the General, Mobs, & Boss config files. 

The thing is, I actually want to learn this kinda stuff & even make my own mods one day, but I'm struggling to even adjust these settings, so... although I feel kinda dumb for needing to ask (bc everything sounds super simple when I read the page's About section & such):

**Is it possible for me to set it so that mobs are allowed to attack each other, but not me?**

I've played the BLISS pack a few times (that's how I discovered Apathy) & really liked the configuration there, but I don't want to get rid of spiders nor let the Illagers attack me on-sight, so I can't just copy-paste those configs into my own personal pack. 

( I'm pretty sure I figured out how to tweak it so they won't attack you unless you attack them first, but that might've been on an older version of the configs maybe (or 1.19.2's are different from 1.20.1, unsure) & I don't really want that on most of the time bc I'm kind of a coward in-game, hahaha... OTL )

**Comment by quat1024** [comment]
Hi, sorry I'm late, it was finals week. Apathy should not prevent things like "mob infighting when a skeleton shoots another mob." That should still happen.

Most mobs have a "target", which is whatever thing they're aggroed against. Usually the target is the closest player, but if a skeleton shoots a zombie the zombie will target the skeleton, stuff like that. (I'm sure you're familiar with this.) When a mob wants to pick a new target it calls the function `setTarget`. Apathy hooks this function and has the option to "cancel" it, which means the function call will not happen.

* Suppose a zombie wants to target mob X.
* If X is a player entity, **and** the rule says the mob *isn't* allowed to attack that player, Apathy cancels the function call.
  * The result is that nothing happens, and the zombie keeps targeting whatever it was targeting previously, which can be nothing.
* Otherwise, Apathy lets the function call happen normally.
  * The result is that the zombie *is* allowed to target X.

https://github.com/quat1024/apathy/blob/ef1e39902f6b20e2eea2416994cc670f14e68288/common-1.20.1/src/main/java/agency/highlysuspect/apathy/mixin/MobMixin.java#L64-L65

So, situations where Apathy will allow the zombie to target X:
* If X is not a player. (This allows all mob infighting to happen.)
* If the Apathy rule says the zombie *is* allowed to attack this player.

> I've played the BLISS pack a few times (that's how I discovered Apathy) & really liked the configuration there, but I don't want to get rid of spiders nor let the Illagers attack me on-sight, so I can't just copy-paste those configs into my own personal pack.

Try one of these:

<details><summary>Bliss's rule json without the vindicator, pillager, piglin_brute, vex, ravager, evoker exceptions</summary>

```json
{
  "rules": [
    {
      "predicate": {
        "difficulties": [
          "hard"
        ],
        "type": "apathy:difficulty_is"
      },
      "type": "apathy:allow_if"
    },
    {
      "predicate": {
          "type": "apathy:attacker_is_boss"
      },
      "type": "apathy:allow_if"
    },
    {
      "predicate": {
        "timeout": 1200,
        "type": "apathy:revenge_timer"
      },
      "type": "apathy:allow_if"
    },
    {
      "predicate": {
        "difficulties": [
          "easy"
        ],
        "type": "apathy:difficulty_is"
      },
      "type": "apathy:deny_if"
    }
  ],
  "type": "apathy:chain"
}
```

</details>

<details><summary>That, but the "revenge timer" is also removed</summary>

```json
{
  "rules": [
    {
      "predicate": {
        "difficulties": [
          "hard"
        ],
        "type": "apathy:difficulty_is"
      },
      "type": "apathy:allow_if"
    },
    {
      "predicate": {
          "type": "apathy:attacker_is_boss"
      },
      "type": "apathy:allow_if"
    },
    {
      "predicate": {
        "difficulties": [
          "easy"
        ],
        "type": "apathy:difficulty_is"
      },
      "type": "apathy:deny_if"
    }
  ],
  "type": "apathy:chain"
}
```

</details>

Looks like Bliss uses [In Control](https://modrinth.com/mod/in-control) to remove spiders, [here's its config file](https://github.com/VazkiiMods/Bliss/blob/1f56661bbdbc1fd89ecad77703dbbd405ceddbd7/config/incontrol/spawn.json#L1-L17). Apathy doesn't do anything with mob spawns.

*(hmm, the In Control config file looks a lot simpler than apathy's, maybe i should take some notes...)*

**Comment by Full-Course-Identity** [comment]
Oh my Gosh, thank you so much for this in-depth response — 1. I hope your finals are going &/or went well!!!, & 2. I’ll try these here shortly & let you know if anything seems amiss : D I really appreciate your effort & patience here, it means a lot!
