### ISSUE TITLE
Apathy Config replacing undergarden mob entries with minecraft:pig. [Forge 1.18.2]

### ISSUE THREAD

**Issue by Bobisnotap** [quat1024/apathy#9]
Game Version: 1.18.2
Apathy Version: 1.18.2-forge-2.4
Forge Version: 40.1.51
Issue: My apathy config keeps replacing the entries `undergarden:gwib` and `undergarden:forgotten_guardian` with `minecraft:pig` in the `mobSet` section every time I reload the game. 
Notes: Disabling `runRuleOptimizer` does not prevent this. 
I am currently not using the json system or any of the debug settings.
Everything else seems to be working as intended.
Ask if you want my modlist and config if those will help!
Many thanks in advance.

**Comment by quat1024** [comment]
lolwut

**Comment by FoggyWizard** [comment]
Same version, same issue. It's changing the clay golems from It Takes a Pillage and the Guards from Guard villagers to the same pig entry. Which is frustrating since I'm just trying to regain village access while using the cursed ring from Forbidden and Arcanus.

**Comment by quat1024** [comment]
hmm, might be a mod load order thing

**Comment by quat1024** [comment]
Knowing that it happens to all modded entities definitely makes this bug less scary LOL, i was like ok so what kind of freak incompatibility is there with *specifically undergarden*

Apathy initializes early compared to a lot of forge mods so it's probably finding stuff that doesn't exist in the registry yet; it replaces them with `pig` for the same reason that placing a mob spawner item results in a pig spawner. Honestly it'd probably be a good idea for Apathy to not load the config at all until you get into the world which will take care of that.

**Comment by quat1024** [comment]
The version labeled `2.4.1` for recent versions (1.18, 1.19), or `1.1.1` for the older Fabric-only versions, loads the config file only when the server starts or on `/reload`/`/apathy reload`, so they *should* fix this issue. Otherwise they've received minimal testing tbh, there's a total of twelve combinations of "client or server" + "modloader" + "game version" and I don't have any kind of automated test harness... If Curseforge is slow, pick them up here https://modrinth.com/mod/apathy/versions
